version: '3.8'

services:
  recommendation:
    build: .
    container_name: recommendation-system
    ports:
      - "8081:8081" # Port for generator
      - "8082:8082" # Port for invoker
    networks:
      - recommendation-network

  redis:
    image: "redis:alpine"
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - recommendation-network

networks:
  recommendation-network:
    driver: bridge
